<div class="modal fade" id="modal-new" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?= ucfirst($this->translate('Add phone')) ?></h4>
            </div>
            <div class="modal-body">                
                <fieldset>
                    <form class="api-form form-horizontal" action="/user/add-phone" method="POST" name="form-add-phone" role="form" >
                        <!-- Form Name -->                        
                        <input name="method" value="POST" type="hidden">         
                        <div class="form-group">
                            <div class="col-md-2"></div>                
                            <label class="col-md-4 control-label" id="label-add-user" for="input-add-ddd"><?= $this->translate('DDD') ?>: </label>
                            <div class="col-md-4">
                                <input class="form-control input-md" value="" id="input-add-ddd" name="ddd" type="number" placeholder="<?= $this->translate('DDD') ?>">
                            </div>                                      
                            <div class="col-md-2"></div>                
                        </div>                                          
                        <div class="form-group">
                            <div class="col-md-2"></div>                
                            <label class="col-md-4 control-label" id="label-add-user" for="input-add-phone"><?= $this->translate('Phone') ?>: </label>
                            <div class="col-md-4">
                                <input class="form-control input-md" value="" id="input-add-phone" name="phone" type="number" placeholder="<?= $this->translate('Phone') ?>">
                            </div>                                      
                            <div class="col-md-2"></div>                
                        </div>                                          
                        <div class="form-group">
                            <div class="col-md-2"></div>                
                            <div class="col-md-8">
                                <button data-clone-field="[data-clone=add-user-phone]" data-clone-target="#form-user-phone" data-add="/user/add-phone.json" name="add-phone" type="button" class="btn btn-success pull-right">                                        
                                    <?= ucfirst($this->translate('Add phone')) ?>
                                </button>                                                                                        
                            </div>
                            <div class="col-md-2"></div>                
                        </div>
                    </form>                    
                </fieldset>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>