<div class="modal fade" id="modal-new" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?= ucfirst($this->translate('Add address')) ?></h4>
            </div>
            <div class="modal-body">                
                <fieldset>                    
                    <form  data-clone-field="[data-clone=add-user-address]" data-clone-target="#form-user-address"  class="form-horizontal" action="/user/add-address.json" method="POST">                        
                        <div class="row">
                            <div class="form-suggestion">
                                <?= $this->translate('Company Address'); ?>
                            </div>
                            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                                <div class="input-group">                                    
                                    <input id="address-nickname" name="address-nickname" type="text" placeholder="<?= $this->translate('Enter alias of your address') ?>" class="form-control input-md" required>
                                </div>                        
                            </div>                                
                            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                <div class="input-group">
                                    <input id="cep" name="cep" data-postmon="address-search" type="text" placeholder="<?= $this->translate('Enter CEP of your address') ?>" data-mask="({mask: '99999-999','clearIncomplete': true})" class="form-control input-md" required>
                                </div>
                            </div>                                
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                <div class="input-group">
                                    <input id="street" name="street" type="text" placeholder="<?= $this->translate('Enter address of your Company') ?>" class="form-control input-md" required readonly>
                                </div>
                            </div>        
                            <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
                                <div class="input-group">
                                    <input id="address-number" name="address-number" type="text" placeholder="<?= $this->translate('Enter address number') ?>" class="form-control input-md" required>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                <div class="input-group">
                                    <input id="complement" name="complement" type="text" placeholder="<?= $this->translate('Enter complement of your address') ?>" class="form-control input-md">
                                </div>                        
                            </div>                                
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                                <div class="input-group">
                                    <input id="district" name="district" type="text" placeholder="<?= $this->translate('Enter district of your address') ?>" class="form-control input-md" required readonly>
                                </div>                        
                            </div>
                            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                                <div class="input-group">
                                    <input id="city" name="city" type="text" placeholder="<?= $this->translate('Enter city of your address') ?>" class="form-control input-md" required readonly>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
                                <div class="input-group">
                                    <input id="state-name" name="state-name" type="hidden">
                                    <input id="state" name="state" type="text" placeholder="<?= $this->translate('Enter state of your address') ?>" class="form-control input-md" required readonly>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                                <div class="input-group">
                                    <input id="country-code" name="country-code" type="hidden">
                                    <input id="country" name="country" type="text" placeholder="<?= $this->translate('Enter country of your address') ?>" class="form-control input-md" required readonly>
                                </div>                        
                            </div>
                        </div>
                        <div class="text-center">        
                            <input type="hidden" name="lat" id="lat">
                            <input type="hidden" name="lng" id="lng">
                            <button data-clone-field="[data-clone=add-user-address]" data-clone-target="#form-user-address" data-add="/user/add-address.json" name="add-address" type="submit" class="btn btn-success pull-right">
                                <?= ucfirst($this->translate('Add address')) ?>
                            </button>     
                        </div>
                    </form>

                </fieldset>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>