<div class="app-container app-login">
    <div class="flex-center">        
        <div class="app-header"></div>
        <div class="app-body">
            <div class="loader-container text-center">
                <div class="icon">
                    <div class="sk-folding-cube">
                        <div class="sk-cube1 sk-cube"></div>
                        <div class="sk-cube2 sk-cube"></div>
                        <div class="sk-cube4 sk-cube"></div>
                        <div class="sk-cube3 sk-cube"></div>
                    </div>
                </div>
                <div class="title">Logging in...</div>
            </div>
            <div class="app-block">
                <div class="app-right-section">                    
                    <div class="app-brand"><img class="lazy-loaded" width="210px" height="66px" alt="<?= $this->translate('Application Name') ?>" src="<?= $this->defaultCompany->getImage()->getUrl() ?>"></div>                                        
                    <div class="app-info">

                        <ul class="list">
                            <li>
                                <div class="icon">
                                    <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                                </div>
                                <div class="title">Increase <b>Productivity</b></div>
                            </li>
                            <li>
                                <div class="icon">
                                    <i class="fa fa-cubes" aria-hidden="true"></i>
                                </div>
                                <div class="title">Lot of <b>Components</b></div>
                            </li>
                            <li>
                                <div class="icon">
                                    <i class="fa fa-usd" aria-hidden="true"></i>
                                </div>
                                <div class="title">Forever <b>Free</b></div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="app-form">
                    <div class="form-suggestion">
                        <?= $this->translate('Create Account'); ?>
                    </div>
                    <form id="create-account-form" class="form-horizontal" data-success-url="/user/profile" action="/user/create-account.json" method="POST">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">
                                <i class="fa fa-paper-plane" aria-hidden="true"></i></span>
                            <input id="name" name="name" type="text" placeholder="<?= $this->translate('Enter your name') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon2">
                                <i class="fa fa-envelope" aria-hidden="true"></i></span>
                            <input id="email" data-mask="({mask: '*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,2}]',greedy: false,onBeforePaste: function (pastedValue, opts) {pastedValue = pastedValue.toLowerCase();return pastedValue.replace('mailto:', '');},definitions: {'*': {validator:'[0-9A-Za-z!#$%&\'*+/=?^_`{|}~\-]',cardinality: 1,casing: 'lower'}}})" name="email" type="text" placeholder="<?= $this->translate('Enter your e-mail') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon3">
                                <i class="fa fa-user" aria-hidden="true"></i></span>
                            <input id="username" data-user-in-use="/user/user-in-use/username/" data-mask-regex="({regex: '[a-za-zA-Z0-9]{3,15}'})" name="username" type="text" placeholder="<?= $this->translate('Enter your username') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon4">
                                <i class="fa fa-key" aria-hidden="true"></i></span>
                            <input id="password" name="password" type="password" data-validation-disabled="strength" data-validation-strength="2" placeholder="<?= $this->translate('Enter a password') ?>" class="form-control input-md" required>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon5">
                                <i class="fa fa-check" aria-hidden="true"></i></span>
                            <input id="password" name="confirm-password" type="password" data-validation="confirmation" data-validation-confirm="password"  placeholder="<?= $this->translate('Confirm your Password') ?>" class="form-control input-md" required>
                        </div>
                        <div class="text-center">                                                            
                            <button data-save="/user/create-account.json" data-success-url="<?= $this->login_referrer ?: '/user/profile' ?>" id="signup" name="signup" class="btn btn-success btn-submit"><?= $this->translate('Register') ?></button>
                        </div>
                    </form>
                    <!--
                    <div class="form-line">
                        <div class="title">OR</div>
                    </div>
                    <div class="form-footer">
                        <button type="button" class="btn btn-default btn-sm btn-social __facebook">
                            <div class="info">
                                <i class="icon fa fa-facebook-official" aria-hidden="true"></i>
                                <span class="title">Register w/ Facebook</span>
                            </div>
                        </button>
                    </div>
                    -->
                    <a class="pull-left" href="/user/login"><?= $this->translate('Login') ?></a>       
                    <a class="pull-right" href="/user/forgot-password"><?= $this->translate('Forgot password ?') ?></a>
                </div>
            </div>
        </div>
        <div class="app-footer">
        </div>
    </div>
</div>