<form class="form-horizontal" method="POST">
    <fieldset>
        <!-- Form Name -->
        <legend><?= $this->translate('Create User'); ?></legend>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="name"><?= $this->translate('Name') ?></label>  
            <div class="col-md-4">
                <input id="name" name="name" type="text" placeholder="<?= $this->translate('Enter your name') ?>" class="form-control input-md" required>
            </div>
        </div>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="username"><?= $this->translate('Username') ?></label>  
            <div class="col-md-4">
                <input id="name" data-mask-regex="({regex: '[a-za-zA-Z0-9]{3,15}'})" data-validation="server" data-validation-url="/user/user-exists.json" name="username" type="text" placeholder="<?= $this->translate('Enter your username') ?>" class="form-control input-md" required>
            </div>
        </div>

        <!-- Password input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="password"><?= $this->translate('Password') ?></label>
            <div class="col-md-4">
                <input id="password" name="password" type="password" data-validation="strength" data-validation-strength="2" placeholder="<?= $this->translate('Enter a password') ?>" class="form-control input-md" required>
            </div>
        </div>
        <!-- Confirm input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="confirm-password"><?= $this->translate('Confirm your Password') ?></label>
            <div class="col-md-4">
                <input id="password" name="confirm-password" type="password" data-validation="confirmation" data-validation-confirm="password"  placeholder="<?= $this->translate('Confirm your Password') ?>" class="form-control input-md" required>
            </div>
        </div>

        <!-- Button -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="signup"></label>
            <div class="col-md-4">
                <button id="signup" name="signup" class="btn btn-success"><?= $this->translate('Sign Up') ?></button>
            </div>
        </div>    
    </fieldset>
</form>
