<form class="form-horizontal" action="/user/login" method="POST">
    <fieldset>
        <!-- Form Name -->
        <legend>Login</legend>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="username"><?= $this->translate('Username') ?></label>  
            <div class="col-md-4">
                <input id="username" data-mask-regex="({regex: '[a-za-zA-Z0-9]{3,15}'})" data-validation="length" data-validation-backend="x" data-validation-length="3-15" name="username" type="text" placeholder="<?= $this->translate('Enter your Username') ?>" class="form-control input-md" required>
            </div>
        </div>
        <!-- Password input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="password"><?= $this->translate('Password') ?></label>
            <div class="col-md-4">
                <input id="password" name="password" type="password" data-validation="required" placeholder="<?= $this->translate('Enter a password') ?>" class="form-control input-md" required>
            </div>
        </div>
        <!-- Button -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="login"></label>
            <div class="col-md-4">
                <button id="login" name="login" class="btn btn-success"><?= $this->translate('Login') ?></button>
            </div>
        </div>
        <a class="pull-left" href="/user/create-account"><?= $this->translate('Create Account') ?></a>       
        <a class="pull-right" href="/user/forgot-password"><?= $this->translate('Forgot password ?') ?></a>
    </fieldset>
</form>